/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import { DoubleSide, FrontSide } from 'three'

export function Rose(props) {
  const { nodes, materials } = useGLTF('/rose/rose2.glb')

  const matRose = (
    <MeshTransmissionMaterial
      thickness={0.01}
      side={FrontSide}
      transmission={1}
      roughness={0.005}
      metalness={0.1}
      reflectivity={0.5}
      backsideResolution={512}
      resolution={512}
      samples={1}
      color={'#ff1111'}
      chromaticAberration={0.2}
    ></MeshTransmissionMaterial>
  )
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Stem'
        castShadow
        receiveShadow
        geometry={nodes.Stem.geometry}
        material={materials.green}
        position={[0.01582, 0.18058, -0.08771]}
        rotation={[1.1232, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'Stem' }}
      />
      <mesh
        name='petals021'
        castShadow
        receiveShadow
        geometry={nodes.petals021.geometry}
        position={[0.03869, 0.32278, -0.11959]}
        rotation={[1.92032, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'petals.021' }}
      >
        {matRose}
      </mesh>
      <mesh
        name='petals001'
        castShadow
        receiveShadow
        geometry={nodes.petals001.geometry}
        position={[0.03727, 0.30462, -0.06339]}
        rotation={[1.92032, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'petals.001' }}
      >
        {matRose}
      </mesh>
      <mesh
        name='petals013'
        castShadow
        receiveShadow
        geometry={nodes.petals013.geometry}
        position={[0.07679, 0.34146, -0.12545]}
        rotation={[1.92032, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'petals.013' }}
      >
        {matRose}
      </mesh>
    </group>
  )
}
