/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function Rose(props) {
  const { nodes, materials } = useGLTF('/rose/rose2.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        name='Stem'
        castShadow
        receiveShadow
        geometry={nodes.Stem.geometry}
        material={materials.green}
        position={[0.01582, 0.18058, -0.08771]}
        rotation={[1.1232, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'Stem' }}
      >
        <meshPhysicalMaterial transmission={1} thickness={1} roughness={0} color={'#008800'} />
      </mesh>
      <mesh
        name='petals021'
        castShadow
        receiveShadow
        geometry={nodes.petals021.geometry}
        position={[0.03869, 0.32278, -0.11959]}
        rotation={[1.92032, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'petals.021' }}
      >
        <meshPhysicalMaterial transmission={1} thickness={1} roughness={0} color={'#ff0000'} />
      </mesh>
      <mesh
        name='petals001'
        castShadow
        receiveShadow
        geometry={nodes.petals001.geometry}
        position={[0.03727, 0.30462, -0.06339]}
        rotation={[1.92032, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'petals.001' }}
      >
        <meshPhysicalMaterial transmission={1} thickness={1} roughness={0} color={'#ff0000'} />
      </mesh>
      <mesh
        name='petals013'
        castShadow
        receiveShadow
        geometry={nodes.petals013.geometry}
        position={[0.07679, 0.34146, -0.12545]}
        rotation={[1.92032, 0, -Math.PI / 2]}
        scale={0.00136}
        userData={{ name: 'petals.013' }}
      >
        <meshPhysicalMaterial transmission={1} thickness={1} roughness={0} color={'#ff0000'} />
      </mesh>
    </group>
  )
}
